sudo: required
services:
  - docker

before_install:
  - yes | sudo gem install rake
  - docker build -t karthikgirraj/resume-app -f app.Dockerfile .
  - docker build -t karthikgirraj/resume-db -f db.Dockerfile .
  - docker build -t karthikgirraj/resume-webserver -f webserver.Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push karthikgirraj/resume-app
  - docker push karthikgirraj/resume-db
  - docker push karthikgirraj/resume-webserver

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: resume-docker
  env: ResumeDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-577683050298
  bucker_path: resume-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY