branch-defaults:
  Elastic_Beanstalk:
    environment: resume-crudbooster2-dev
    group_suffix: null
global:
  application_name: resume-crudbooster2
  branch: null
  default_ec2_keyname: AWS_MUMBAI
  default_platform: PHP 7.2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
